version: '3.8'

services:
  api:
    build: .
    container_name: fastapi-container
    ports:
      - "8443:8443"
    volumes:
      - .:/app
      - ./certs:/app/certs:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 8443
      --ssl-keyfile=/app/certs/key.pem 
      --ssl-certfile=/app/certs/cert.pem